# Lab 2: numpy

#### Practice Exercise 1

Create the following NumPy arrays:
1. A 1-D array called zeros having 10 elements and all the elements are set to zero.
2. A 1-D array called vowels having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’.
3. A 2-D array called ones having 2 rows and 5 columns and all the elements are set to 1 and dtype as int.
4. Use nested Python lists to create a 2-D array called myarray1 having 3 rows and 3 columns and store the following data: 2.7,  0,  -2,  3.4,  10.6,  0,  -19 99.9 13
5. A 2-D array called myarray2 using arange() having 3 rows and 5 columns with start value = 4, step size 4 and dtype as float


In [ ]:
import numpy as np

# A 1-D array called zeros having 10 elements set to zero
zeros = np.zeros(10)

# A 1-D array called vowels with elements 'a', 'e', 'i', 'o', 'u'
vowels = np.array(['a', 'e', 'i', 'o', 'u'])

# A 2-D array called ones with 2 rows and 5 columns set to 1 (int)
ones = np.ones((2, 5), dtype=int)

# A 2-D array called myarray1 with specific elements using nested lists
myarray1 = np.array([
    [2.7, 0, -2],
    [3.4, 10.6, 0],
    [-19, 99.9, 13]
])

# A 2-D array called myarray2 using arange with start=4, step=4, and float dtype
myarray2 = np.arange(4, 64, 4).reshape(3, 5).astype(float)

print("zeros:", zeros)
print("vowels:", vowels)
print("ones:\n", ones)
print("myarray1:\n", myarray1)
print("myarray2:\n", myarray2)





zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
vowels: ['a' 'e' 'i' 'o' 'u']
ones:
 [[1 1 1 1 1]
 [1 1 1 1 1]]
myarray1:
 [[  2.7   0.   -2. ]
 [  3.4  10.6   0. ]
 [-19.   99.9  13. ]]
myarray2:
 [[ 4.  8. 12. 16. 20.]
 [24. 28. 32. 36. 40.]
 [44. 48. 52. 56. 60.]]


Using the arrays created in Question above, write NumPy commands for the following:
1. Find the dimensions, shape, size, data type of the items and itemsize of arrays zeros, vowels, ones, myarray1 and myarray2.
2. Reshape the array ones to have all the 10 elements in a single row.
3. Display the 2nd and 3rd element of the array vowels.
4. Display all elements in the 2nd and 3rd row of the array myarray1.
5. Display the elements in the 1st and 2nd column of the array myarray1.
6. Display the elements in the 1st column of the 2nd and 3rd row of the array myarray1.
7. Reverse the array of vowels.

In [ ]:
# Find dimensions, shape, size, data type of the items and itemsize of arrays
print("zeros - dimensions:", zeros.ndim)
print("zeros - shape:", zeros.shape)
print("zeros - size:", zeros.size)
print("zeros - data type:", zeros.dtype)
print("zeros - itemsize:", zeros.itemsize)

print("vowels - dimensions:", vowels.ndim)
print("vowels - shape:", vowels.shape)
print("vowels - size:", vowels.size)
print("vowels - data type:", vowels.dtype)
print("vowels - itemsize:", vowels.itemsize)

print("ones - dimensions:", ones.ndim)
print("ones - shape:", ones.shape)
print("ones - size:", ones.size)
print("ones - data type:", ones.dtype)
print("ones - itemsize:", ones.itemsize)

print("myarray1 - dimensions:", myarray1.ndim)
print("myarray1 - shape:", myarray1.shape)
print("myarray1 - size:", myarray1.size)
print("myarray1 - data type:", myarray1.dtype)
print("myarray1 - itemsize:", myarray1.itemsize)

print("myarray2 - dimensions:", myarray2.ndim)
print("myarray2 - shape:", myarray2.shape)
print("myarray2 - size:", myarray2.size)
print("myarray2 - data type:", myarray2.dtype)
print("myarray2 - itemsize:", myarray2.itemsize)

# Reshape the array ones to have all 10 elements in a single row
ones_reshaped = ones.reshape(1, -1)
print("ones reshaped to a single row:\n", ones_reshaped)

# Display the 2nd and 3rd element of the array vowels
print("2nd and 3rd elements of vowels:", vowels[1:3])

# Display all elements in the 2nd and 3rd row of the array myarray1
print("Elements in the 2nd and 3rd row of myarray1:\n", myarray1[1:3, :])

# Display the elements in the 1st and 2nd column of the array myarray1
print("Elements in the 1st and 2nd column of myarray1:\n", myarray1[:, :2])

# Display the elements in the 1st column of the 2nd and 3rd row of the array myarray1
print("Elements in the 1st column of the 2nd and 3rd row of myarray1:\n", myarray1[1:3, 0])

# Reverse the array of vowels
vowels_reversed = vowels[::-1]
print("Reversed vowels:", vowels_reversed)




zeros - dimensions: 1
zeros - shape: (10,)
zeros - size: 10
zeros - data type: float64
zeros - itemsize: 8
vowels - dimensions: 1
vowels - shape: (5,)
vowels - size: 5
vowels - data type: <U1
vowels - itemsize: 4
ones - dimensions: 2
ones - shape: (2, 5)
ones - size: 10
ones - data type: int64
ones - itemsize: 8
myarray1 - dimensions: 2
myarray1 - shape: (3, 3)
myarray1 - size: 9
myarray1 - data type: float64
myarray1 - itemsize: 8
myarray2 - dimensions: 2
myarray2 - shape: (3, 5)
myarray2 - size: 15
myarray2 - data type: float64
myarray2 - itemsize: 8
ones reshaped to a single row:
 [[1 1 1 1 1 1 1 1 1 1]]
2nd and 3rd elements of vowels: ['e' 'i']
Elements in the 2nd and 3rd row of myarray1:
 [[  3.4  10.6   0. ]
 [-19.   99.9  13. ]]
Elements in the 1st and 2nd column of myarray1:
 [[  2.7   0. ]
 [  3.4  10.6]
 [-19.   99.9]]
Elements in the 1st column of the 2nd and 3rd row of myarray1:
 [  3.4 -19. ]
Reversed vowels: ['u' 'o' 'i' 'e' 'a']


Using the arrays created in Question above, write NumPy commands for the following:
1. Divide all elements of array ones by 3.
2. Add the arrays myarray1 and myarray2.
3. Subtract myarray1 from myarray2 and store the result in a new array.
4. Multiply myarray1 and myarray2 elementwise.
5. Do the matrix multiplication of myarray1 and myarray2 and store the result in a new array myarray3.
6. Divide myarray1 by myarray2.
7. Find the cube of all elements of myarray1 and divide the resulting array by 2.
8. Find the square root of all elements of myarray2   and divide the resulting array by 2. The result  should be rounded to two places of decimals.

In [ ]:
# Adjust myarray2 to match the shape of myarray1 by selecting the first 3 columns
myarray2_adjusted = myarray2[:, :3]

# Add the adjusted arrays
sum_arrays = myarray1 + myarray2_adjusted
print("Sum of myarray1 and myarray2_adjusted:\n", sum_arrays)

# Subtract myarray1 from the adjusted myarray2 and store the result in a new array
subtracted_array = myarray2_adjusted - myarray1
print("Result of myarray2_adjusted - myarray1:\n", subtracted_array)

# Multiply myarray1 and the adjusted myarray2 elementwise
elementwise_product = myarray1 * myarray2_adjusted
print("Elementwise product of myarray1 and myarray2_adjusted:\n", elementwise_product)

# Do the matrix multiplication of myarray1 and myarray2_adjusted
# Note: We need to ensure proper shape for matrix multiplication, so we use transpose if necessary.
myarray3 = np.dot(myarray1, myarray2_adjusted.T)
print("Matrix multiplication of myarray1 and myarray2_adjusted (myarray3):\n", myarray3)

# Divide myarray1 by the adjusted myarray2
division_result = myarray1 / myarray2_adjusted
print("Division of myarray1 by myarray2_adjusted:\n", division_result)

# Find the cube of all elements of myarray1 and divide the resulting array by 2
cubed_divided = (myarray1 ** 3) / 2
print("Cubed elements of myarray1 divided by 2:\n", cubed_divided)

# Find the square root of all elements of myarray2_adjusted and divide the resulting array by 2. Round to two decimal places.
sqrt_divided = np.round(np.sqrt(myarray2_adjusted) / 2, 2)
print("Square root of elements of myarray2_adjusted divided by 2 (rounded to 2 decimals):\n", sqrt_divided)


Sum of myarray1 and myarray2_adjusted:
 [[  6.7   8.   10. ]
 [ 27.4  38.6  32. ]
 [ 25.  147.9  65. ]]
Result of myarray2_adjusted - myarray1:
 [[  1.3   8.   14. ]
 [ 20.6  17.4  32. ]
 [ 63.  -51.9  39. ]]
Elementwise product of myarray1 and myarray2_adjusted:
 [[  10.8    0.   -24. ]
 [  81.6  296.8    0. ]
 [-836.  4795.2  676. ]]
Matrix multiplication of myarray1 and myarray2_adjusted (myarray3):
 [[-1.3200e+01  8.0000e-01  1.4800e+01]
 [ 9.8400e+01  3.7840e+02  6.5840e+02]
 [ 8.7920e+02  2.7572e+03  4.6352e+03]]
Division of myarray1 by myarray2_adjusted:
 [[ 0.675       0.         -0.16666667]
 [ 0.14166667  0.37857143  0.        ]
 [-0.43181818  2.08125     0.25      ]]
Cubed elements of myarray1 divided by 2:
 [[ 9.841500e+00  0.000000e+00 -4.000000e+00]
 [ 1.965200e+01  5.955080e+02  0.000000e+00]
 [-3.429500e+03  4.985015e+05  1.098500e+03]]
Square root of elements of myarray2_adjusted divided by 2 (rounded to 2 decimals):
 [[1.   1.41 1.73]
 [2.45 2.65 2.83]
 [3.32 3.46 3.6

Using the arrays created above, write NumPy commands for the following:
1. Find the transpose of ones and myarray2.
2. Sort the array vowels in reverse.
3. Sort the array myarray1 such that it brings the lowest value of the column in the first row and so on.

In [ ]:
import numpy as np

# Assume the arrays `ones`, `vowels`, `myarray1`, and `myarray2` are already defined from the previous steps.

# Find the transpose of the array `ones`
transpose_ones = ones.T
print("Transpose of array ones:\n", transpose_ones)

# Find the transpose of `myarray2`
transpose_myarray2 = myarray2.T
print("\nTranspose of myarray2:\n", transpose_myarray2)

# Sort the array `vowels` in reverse order
sorted_vowels_reverse = np.sort(vowels)[::-1]
print("\nVowels sorted in reverse order:\n", sorted_vowels_reverse)

# Sort `myarray1` such that it brings the lowest value of each column in the first row and so on.
# Use np.sort() along axis 0 (column-wise sort)
sorted_myarray1 = np.sort(myarray1, axis=0)
print("\nmyarray1 sorted column-wise (lowest value in first row):\n", sorted_myarray1)




Transpose of array ones:
 [[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]

Transpose of myarray2:
 [[ 4. 24. 44.]
 [ 8. 28. 48.]
 [12. 32. 52.]
 [16. 36. 56.]
 [20. 40. 60.]]

Vowels sorted in reverse order:
 ['u' 'o' 'i' 'e' 'a']

myarray1 sorted column-wise (lowest value in first row):
 [[-19.    0.   -2. ]
 [  2.7  10.6   0. ]
 [  3.4  99.9  13. ]]


Create a 2-D array called myarray4 using arange() having 14 rows and 3 columns with start value = -1, step size 0.25 having. Split this array row wise into 3 equal parts and print the result.

In [ ]:
import numpy as np

# Create a 2-D array called myarray4 with 14 rows and 3 columns, start value -1, step size 0.25
myarray4 = np.arange(-1, -1 + 14 * 3 * 0.25, 0.25).reshape(14, 3)
print("myarray4:\n", myarray4)

# Split the array row-wise into 3 equal parts
split_arrays = np.array_split(myarray4, 3, axis=0)
print("\nSplit arrays:")
for i, arr in enumerate(split_arrays, start=1):
    print(f"Part {i}:\n", arr)





myarray4:
 [[-1.   -0.75 -0.5 ]
 [-0.25  0.    0.25]
 [ 0.5   0.75  1.  ]
 [ 1.25  1.5   1.75]
 [ 2.    2.25  2.5 ]
 [ 2.75  3.    3.25]
 [ 3.5   3.75  4.  ]
 [ 4.25  4.5   4.75]
 [ 5.    5.25  5.5 ]
 [ 5.75  6.    6.25]
 [ 6.5   6.75  7.  ]
 [ 7.25  7.5   7.75]
 [ 8.    8.25  8.5 ]
 [ 8.75  9.    9.25]]

Split arrays:
Part 1:
 [[-1.   -0.75 -0.5 ]
 [-0.25  0.    0.25]
 [ 0.5   0.75  1.  ]
 [ 1.25  1.5   1.75]
 [ 2.    2.25  2.5 ]]
Part 2:
 [[2.75 3.   3.25]
 [3.5  3.75 4.  ]
 [4.25 4.5  4.75]
 [5.   5.25 5.5 ]
 [5.75 6.   6.25]]
Part 3:
 [[6.5  6.75 7.  ]
 [7.25 7.5  7.75]
 [8.   8.25 8.5 ]
 [8.75 9.   9.25]]


Using the myarray4 created in the above questions, write commands for the following:
1. Find the sum of all elements.
2. Find the sum of all elements row wise
3. Find the sum of all elements column wise.
4. Find the max of all elements.
5. Find the min of all elements in each row.
6. Find the mean of all elements in each row.
7. Find the standard deviation column wise.

In [ ]:
import numpy as np

# Assuming `myarray4` is already defined from the previous step with shape (14, 3).

# Find the sum of all elements in `myarray4`
total_sum = np.sum(myarray4)
print("Sum of all elements in myarray4:", total_sum)

# Find the sum of all elements row-wise
row_sum = np.sum(myarray4, axis=1)
print("\nSum of elements row-wise:\n", row_sum)

# Find the sum of all elements column-wise
column_sum = np.sum(myarray4, axis=0)
print("\nSum of elements column-wise:\n", column_sum)

# Find the maximum of all elements in `myarray4`
max_value = np.max(myarray4)
print("\nMaximum value in myarray4:", max_value)

# Find the minimum value of each row
min_row_values = np.min(myarray4, axis=1)
print("\nMinimum value in each row:\n", min_row_values)

# Find the mean of all elements in each row
row_mean = np.mean(myarray4, axis=1)
print("\nMean of elements in each row:\n", row_mean)

# Find the standard deviation column-wise
column_std_dev = np.std(myarray4, axis=0)
print("\nStandard deviation of elements column-wise:\n", column_std_dev)




Sum of all elements in myarray4: 173.25

Sum of elements row-wise:
 [-2.25  0.    2.25  4.5   6.75  9.   11.25 13.5  15.75 18.   20.25 22.5
 24.75 27.  ]

Sum of elements column-wise:
 [54.25 57.75 61.25]

Maximum value in myarray4: 9.25

Minimum value in each row:
 [-1.   -0.25  0.5   1.25  2.    2.75  3.5   4.25  5.    5.75  6.5   7.25
  8.    8.75]

Mean of elements in each row:
 [-0.75  0.    0.75  1.5   2.25  3.    3.75  4.5   5.25  6.    6.75  7.5
  8.25  9.  ]

Standard deviation of elements column-wise:
 [3.02334666 3.02334666 3.02334666]


#### Practice Exercise 2
Read the coordinates of the capital cities of the world from the country-capital-lat-long-population.csv file. Use NumPy to print the name and coordinates of the capital city closest to the Saudi Arabia capital - Riyadh.

Note that:

1. The Country Name for Saudi Arabia is given as Saudi Arabia in the data.
2. The ‘closeness’ of capital cities from the Saudi Arabia capital is based on the Euclidean distance of their coordinates to those of the Saudi Arabia capital.


Hints:

1. Use read_html() from the Pandas library to read the table.
2. Use the to_numpy() function of the Pandas DataFrame class to convert a DataFrame to a Numpy array
3. Use broadcasting to compute the euclidean distance of capital cities from Riyadh.

In [ ]:
from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv('country-capital-lat-long-population.csv')

print(df.head())

# Calculate the closest capital city to Riyadh
from geopy.distance import great_circle

# Coordinates for Riyadh
riyadh_coordinates = (24.7136, 46.6753)

# Function to find the closest capital city
def find_closest_capital(df, riyadh_coordinates):
    closest_city = None
    closest_distance = float('inf')  # Initialize with infinity

    for index, row in df.iterrows():
        capital_coordinates = (row['Latitude'], row['Longitude'])
        distance = great_circle(riyadh_coordinates, capital_coordinates).kilometers

        if distance < closest_distance:
            closest_distance = distance
            closest_city = row['Capital Type']

    return closest_city, closest_distance

# Call the function and print the result
closest_city, closest_distance = find_closest_capital(df, riyadh_coordinates)
print(f"The closest capital city to Riyadh is {closest_city} at a distance of {closest_distance:.2f} km.")



Saving country-capital-lat-long-population.csv to country-capital-lat-long-population (2).csv
          Country           Capital City  Latitude  Longitude  Population  \
0     Afghanistan                  Kabul   34.5289    69.1725     4011770   
1         Albania        Tiranë (Tirana)   41.3275    19.8189      475577   
2         Algeria  El Djazaïr  (Algiers)   36.7525     3.0420     2693542   
3  American Samoa              Pago Pago  -14.2781  -170.7025       48526   
4         Andorra       Andorra la Vella   42.5078     1.5211       22614   

  Capital Type  
0      Capital  
1      Capital  
2      Capital  
3      Capital  
4      Capital  
The closest capital city to Riyadh is Capital at a distance of 4.31 km.


#### Practical Exercise 2

Use NumPy to:

1. Print the names of the countries of the top 10 capital cities closest to the US capital - Washington DC.

2. Create and print a NumPy array containing the coordinates of the top 10 cities.

In [ ]:
from google.colab import files
import pandas as pd
from geopy.distance import great_circle
import numpy as np

# Upload the CSV file
uploaded = files.upload()

# Load the CSV file into a Pandas DataFrame
df = pd.read_csv('country-capital-lat-long-population.csv')

# Coordinates for Washington, D.C.
dc_coordinates = (38.8951, -77.0364)

# Calculate distances to Washington, D.C.
distances = []
for index, row in df.iterrows():
    capital_coordinates = (row['Latitude'], row['Longitude'])
    distance = great_circle(dc_coordinates, capital_coordinates).kilometers
    distances.append(distance)

# Convert distances to a NumPy array
distances_array = np.array(distances)

# Get the indices of the top 10 closest capitals
top_10_indices = np.argsort(distances_array)[:10]

# Get the names of the countries and coordinates for the top 10 cities
top_10_countries = df['Country'].iloc[top_10_indices].values
top_10_coordinates = df[['Latitude', 'Longitude']].iloc[top_10_indices].to_numpy()

# Print the names of the countries
print("Top 10 closest capital cities to Washington, D.C. (Countries):")
for country in top_10_countries:
    print(country)

# Print the NumPy array containing the coordinates of the top 10 cities
print("\nCoordinates of the top 10 closest capital cities:")
print(top_10_coordinates)



Saving country-capital-lat-long-population.csv to country-capital-lat-long-population (4).csv
Top 10 closest capital cities to Washington, D.C. (Countries):
United States of America
Canada
Bermuda
Bahamas
Cuba
Saint Pierre and Miquelon
Turks and Caicos Islands
Cayman Islands
Haiti
Jamaica

Coordinates of the top 10 closest capital cities:
[[ 38.8951 -77.0364]
 [ 45.4166 -75.698 ]
 [ 32.2915 -64.778 ]
 [ 25.0582 -77.3431]
 [ 23.1195 -82.3785]
 [ 46.7738 -56.1815]
 [ 21.4612 -71.1419]
 [ 19.2866 -81.3744]
 [ 18.5392 -72.335 ]
 [ 17.997  -76.7936]]
